name: Spring Boot CD to Heroku

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: hansab-api
#      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git main
#      uses: AkhileshNS/heroku-deploy@v3.8.8
#      with:

#        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#        heroku_email: ${{secrets.HEROKU_EMAIL}}
#        heroku_app_name: ${{secrets.HEROKU_APP}}
#
#      git push https://heroku:$HEROKU_API_KEY@git.heroku.com/hansab-api.git.git main
##          To https://git.heroku.com/hansab-api.git

